### ISSUE TITLE
JAVA_HOME set to invalid repository

### ISSUE THREAD

**Issue by kasteckis** [vgaidarji/android-github-actions-emulator#6]
Is there any docs how to setup this worklfow?

Currently I'm getting this error.

![image](https://user-images.githubusercontent.com/41127259/76684032-38b3b500-6611-11ea-8d3d-42e609610d97.png)

This is how I setup this workflow in my github actions .yml file.

![image](https://user-images.githubusercontent.com/41127259/76684038-42d5b380-6611-11ea-9d04-92af59cf9e21.png)

**Comment by p13i** [comment]
@vgaidarji , I'm facing the same issue. Do you have any thoughts on how to resolve this issue?

**Comment by kasteckis** [comment]
@p13i I forgot what I exactly did, but I resolved this issue by using some kind of different github action.

See this for reference - https://github.com/kasteckis/SMS-Scheduler/tree/master/.github/workflows

**Comment by vgaidarji** [comment]
The issue with Android Emulator action is known and is tracked under https://github.com/vgaidarji/docker-android/issues/11.

**Comment by gnarea** [comment]
@vgaidarji, isn't that issue preventing the action from working at all? If so, why don't you add a big warning to the README and/or take it down from the GitHub Marketplace?

**Comment by p13i** [comment]
@gnarea +1
